<?php

namespace App\Providers;

use App\Repositories\ActionAMenerRepository;
use Core\Repositories\BaseRepository;
use Core\Repositories\EloquentRepositoryInterface;
use App\Repositories\CategorieRepository;
use App\Repositories\IndicateurRepository;
use App\Repositories\PermissionRepository;
use App\Repositories\RoleRepository;
use App\Repositories\UserRepository;
use App\Repositories\ProgrammeRepository;
use App\Repositories\ProjetRepository;
use App\Repositories\DureeRepository;
use App\Repositories\ActiviteRepository;
use App\Repositories\EActiviteRepository;
use App\Repositories\EActiviteModRepository;
use App\Repositories\ESuiviActiviteModRepository;
use App\Repositories\TacheRepository;
use App\Repositories\PlanDecaissementRepository;
use App\Repositories\DecaissementRepository;
use App\Repositories\SiteRepository;
use App\Repositories\ComposanteRepository;
use App\Repositories\SuiviRepository;
use App\Repositories\ESuiviRepository;
use App\Repositories\StatutRepository;
use App\Repositories\AnoRepository;
use App\Repositories\BailleurRepository;
use App\Repositories\CheckListComRepository;
use App\Repositories\CheckListRepository;
use App\Repositories\SuiviFinancierRepository;
use App\Repositories\FichierRepository;
use App\Repositories\GouvernementRepository;
use App\Repositories\IndicateurModRepository;
use App\Repositories\MaitriseOeuvreRepository;
use App\Repositories\OngComRepository;
use App\Repositories\SuiviFinancierMODRepository;
use App\Repositories\SuiviIndicateurMODRepository;
use App\Repositories\SuiviIndicateurRepository;
use App\Repositories\UniteeDeGestionRepository;
use App\Repositories\UniteeMesureRepository;
use App\Repositories\ValeurCibleIndicateurRepository;
use App\Repositories\PassationRepository;
use App\Repositories\SinistreRepository;
use App\Repositories\ProprieteRepository;
use App\Repositories\NouvelleProprieteRepository;
use App\Repositories\PayeRepository;
use App\Repositories\TypeAnoRepository;
use App\Repositories\ObjectifSpecifiqueRepository;
use App\Repositories\ObjectifGlobauxRepository;
use App\Repositories\ResultatRepository;
use App\Repositories\FormulaireRepository;
use App\Repositories\RappelRepository;
use App\Repositories\AlerteConfigRepository;
use App\Repositories\ReponseRepository;
use App\Repositories\AuditRepository;
use App\Repositories\CritereDeGouvernanceRepository;
use App\Repositories\EnqueteDeCollecteRepository;
use App\Repositories\enquetes_de_gouvernance\ActionAMenerRepository as EnqueteActionAMenerRepository;
use App\Repositories\enquetes_de_gouvernance\CritereDeGouvernanceFactuelRepository;
use App\Repositories\enquetes_de_gouvernance\EvaluationDeGouvernanceRepository as EnqueteEvaluationDeGouvernanceRepository;
use App\Repositories\enquetes_de_gouvernance\FicheDeSyntheseRepository as EnqueteFicheDeSyntheseRepository;
use App\Repositories\enquetes_de_gouvernance\FormulaireDePerceptionDeGouvernanceRepository;
use App\Repositories\enquetes_de_gouvernance\FormulaireFactuelDeGouvernanceRepository;
use App\Repositories\enquetes_de_gouvernance\IndicateurDeGouvernanceFactuelRepository;
use App\Repositories\enquetes_de_gouvernance\OptionDeReponseGouvernanceRepository;
use App\Repositories\enquetes_de_gouvernance\PrincipeDeGouvernanceFactuelRepository;
use App\Repositories\enquetes_de_gouvernance\PrincipeDeGouvernancePerceptionRepository;
use App\Repositories\enquetes_de_gouvernance\QuestionDeGouvernanceRepository;
use App\Repositories\enquetes_de_gouvernance\QuestionDePerceptionDeGouvernanceRepository;
use App\Repositories\enquetes_de_gouvernance\QuestionFactuelDeGouvernanceRepository;
use App\Repositories\enquetes_de_gouvernance\QuestionOperationnelleRepository;
use App\Repositories\enquetes_de_gouvernance\RecommandationRepository as EnqueteRecommandationRepository;
use App\Repositories\enquetes_de_gouvernance\SoumissionDePerceptionRepository;
use App\Repositories\enquetes_de_gouvernance\SoumissionFactuelRepository;
use App\Repositories\enquetes_de_gouvernance\SourceDeVerificationRepository as EnqueteSourceDeVerificationRepository;
use App\Repositories\enquetes_de_gouvernance\SurveyFormRepository as EnqueteSurveyFormRepository;
use App\Repositories\enquetes_de_gouvernance\SurveyReponseRepository as EnqueteSurveyReponseRepository;
use App\Repositories\enquetes_de_gouvernance\SurveyRepository as EnqueteSurveyRepository;
use App\Repositories\enquetes_de_gouvernance\TypeDeGouvernanceFactuelRepository;
use App\Repositories\EvaluationDeGouvernanceRepository;
use App\Repositories\FicheDeSyntheseRepository;
use App\Repositories\FondRepository;
use App\Repositories\FormulaireDeGouvernanceRepository;
use App\Repositories\IndicateurDeGouvernanceRepository;
use App\Repositories\IndicateurValeurRepository;
use App\Repositories\IndicateurValueKeyRepository;
use App\Repositories\OptionDeReponseRepository;
use App\Repositories\OrganisationRepository;
use App\Repositories\PrincipeDeGouvernanceRepository;
use App\Repositories\RecommandationRepository;
use App\Repositories\SuiviCheckListComRepository;
use App\Repositories\TypeDeGouvernanceRepository;
use App\Repositories\SoumissionRepository;
use App\Repositories\SourceDeVerificationRepository;
use App\Repositories\SurveyRepository;
use App\Repositories\SurveyFormRepository;
use App\Repositories\SurveyReponseRepository;
use App\Services\ActionAMenerService;
use App\Services\AuthService;
use App\Services\CategorieService;
use App\Services\IndicateurService;
use App\Services\PermissionService;
use App\Services\ProgrammeService;
use App\Services\ProjetService;
use App\Services\RoleService;
use App\Services\ComposanteService;
use App\Services\UserService;
use App\Services\ActiviteService;
use App\Services\EActiviteService;
use App\Services\EActiviteModService;
use App\Services\ESuiviActiviteModService;
use App\Services\TacheService;
use App\Services\SuiviService;
use App\Services\ESuiviService;
use App\Services\SuiviFinancierService;
use App\Services\StatutService;
use App\Services\AnoService;
use App\Services\BailleurService;
use App\Services\CheckListComService;
use App\Services\CheckListService;
use App\Services\EntrepriseExecutantService;
use App\Services\InstitutionService;
use App\Services\FichierService;
use App\Services\IndicateurModService;
use App\Services\PtaService;
use App\Services\PlanDecaissementService;
use App\Services\DecaissementService;
use App\Services\GouvernementService;
use App\Services\IndicateurCadreLogiqueService;
use App\Services\SiteService;
use App\Services\MaitriseOeuvreService;
use App\Services\MembreMissionDeControleService;
use App\Services\MembreUniteeDeGestionService;
use App\Services\MissionDeControleService;
use App\Services\ModService;
use App\Services\OngCommService;
use App\Services\SuiviCheckListComService;
use App\Services\SuiviFinancierMODService;
use App\Services\SuiviIndicateurMODService;
use App\Services\SuiviIndicateurService;
use App\Services\UniteeDeGestionService;
use App\Services\UniteeMesureService;
use App\Services\PassationService;
use App\Services\SinistreService;
use App\Services\ProprieteService;
use App\Services\NouvelleProprieteService;
use App\Services\PayeService;
use App\Services\TypeAnoService;
use App\Services\TableService;
use App\Services\ObjectifSpecifiqueService;
use App\Services\ObjectifGlobauxService;
use App\Services\ResultatService;
use App\Services\FormulaireService;
use App\Services\RappelService;
use App\Services\AlerteConfigService;
use App\Services\PtabScopeService;
use App\Services\ReponseAnoService;
use App\Services\ReponseService;
use App\Services\AuditService;
use App\Services\CritereDeGouvernanceService;
use App\Services\EnqueteDeCollecteService;
use App\Services\enquetes_de_gouvernance\ActionAMenerService as ActionAMenerGouvernanceService;
use App\Services\enquetes_de_gouvernance\CritereDeGouvernanceFactuelService;
use App\Services\enquetes_de_gouvernance\EvaluationDeGouvernanceService as EvaluationDeGouvernanceEnqueteService;
use App\Services\enquetes_de_gouvernance\FormulaireDePerceptionDeGouvernanceService;
use App\Services\enquetes_de_gouvernance\FormulaireFactuelDeGouvernanceService;
use App\Services\enquetes_de_gouvernance\IndicateurDeGouvernanceFactuelService;
use App\Services\enquetes_de_gouvernance\OptionDeReponseGouvernanceService;
use App\Services\enquetes_de_gouvernance\PrincipeDeGouvernanceFactuelService;
use App\Services\enquetes_de_gouvernance\PrincipeDeGouvernancePerceptionService;
use App\Services\enquetes_de_gouvernance\QuestionOperationnelleService;
use App\Services\enquetes_de_gouvernance\RecommandationService as RecommandationGouvernanceService;
use App\Services\enquetes_de_gouvernance\SoumissionDePerceptionService;
use App\Services\enquetes_de_gouvernance\SoumissionFactuelService;
use App\Services\enquetes_de_gouvernance\SourceDeVerificationService as EnqueteSourceDeVerificationService;
use App\Services\enquetes_de_gouvernance\SurveyFormService as EnqueteSurveyFormService;
use App\Services\enquetes_de_gouvernance\SurveyReponseService as EnqueteSurveyReponseService;
use App\Services\enquetes_de_gouvernance\SurveyService as EnqueteSurveyService;
use App\Services\enquetes_de_gouvernance\TypeDeGouvernanceFactuelService;
use App\Services\EvaluationDeGouvernanceService;
use App\Services\FicheDeSyntheseService;
use App\Services\FondService;
use App\Services\FormulaireDeGouvernanceService;
use App\Services\IndicateurDeGouvernanceService;
use App\Services\IndicateurValueKeyService;
use App\Services\OptionDeReponseService;
use App\Services\OrganisationService;
use App\Services\PrincipeDeGouvernanceService;
use App\Services\RecommandationService;
use App\Services\SoumissionService;
use App\Services\SourceDeVerificationService;
use App\Services\SurveyService;
use App\Services\SurveyFormService;
use App\Services\SurveyReponseService;
use App\Services\TypeDeGouvernanceService;
use Core\Services\Contracts\BaseService;

use Core\Services\Contracts\AbstractServiceInterface;
use Core\Services\Interfaces\ActionAMenerServiceInterface;
use Core\Services\Interfaces\AuthServiceInterface;
use Core\Services\Interfaces\CategorieServiceInterface;
use Core\Services\Interfaces\IndicateurServiceInterface;
use Core\Services\Interfaces\PermissionServiceInterface;
use Core\Services\Interfaces\RoleServiceInterface;
use Core\Services\Interfaces\ComposanteServiceInterface;
use Core\Services\Interfaces\UserServiceInterface;
use Core\Services\Interfaces\ProjetServiceInterface;
use Core\Services\Interfaces\PtaServiceInterface;
use Core\Services\Interfaces\ProgrammeServiceInterface;
use Core\Services\Interfaces\ActiviteServiceInterface;
use Core\Services\Interfaces\EActiviteServiceInterface;
use Core\Services\Interfaces\EActiviteModServiceInterface;
use Core\Services\Interfaces\ESuiviActiviteModServiceInterface;
use Core\Services\Interfaces\TacheServiceInterface;
use Core\Services\Interfaces\SuiviServiceInterface;
use Core\Services\Interfaces\ESuiviServiceInterface;
use Core\Services\Interfaces\SuiviFinancierServiceInterface;
use Core\Services\Interfaces\StatutServiceInterface;
use Core\Services\Interfaces\AnoServiceInterface;
use Core\Services\Interfaces\BailleurServiceInterface;
use Core\Services\Interfaces\CheckListComServiceInterface;
use Core\Services\Interfaces\CheckListServiceInterface;
use Core\Services\Interfaces\EntrepriseExecutantServiceInterface;
use Core\Services\Interfaces\InstitutionServiceInterface;
use Core\Services\Interfaces\FichierServiceInterface;
use Core\Services\Interfaces\IndicateurModServiceInterface;
use Core\Services\Interfaces\PlanDecaissementServiceInterface;
use Core\Services\Interfaces\DecaissementServiceInterface;
use Core\Services\Interfaces\GouvernementServiceInterface;
use Core\Services\Interfaces\IndicateurCadreLogiqueServiceInterface;
use Core\Services\Interfaces\SiteServiceInterface;
use Core\Services\Interfaces\MaitriseOeuvreServiceInterface;
use Core\Services\Interfaces\MembreMissionDeControleServiceInterface;
use Core\Services\Interfaces\MembreUniteeDeGestionServiceInterface;
use Core\Services\Interfaces\MissionDeControleServiceInterface;
use Core\Services\Interfaces\ModServiceInterface;
use Core\Services\Interfaces\OngCommServiceInterface;
use Core\Services\Interfaces\SuiviCheckListComServiceInterface;
use Core\Services\Interfaces\SuiviFinancierMODServiceInterface;
use Core\Services\Interfaces\SuiviIndicateurMODServiceInterface;
use Core\Services\Interfaces\SuiviIndicateurServiceInterface;
use Core\Services\Interfaces\UniteeDeGestionServiceInterface;
use Core\Services\Interfaces\UniteeMesureServiceInterface;
use Core\Services\Interfaces\PassationServiceInterface;
use Core\Services\Interfaces\SinistreServiceInterface;
use Core\Services\Interfaces\ProprieteServiceInterface;
use Core\Services\Interfaces\NouvelleProprieteServiceInterface;
use Core\Services\Interfaces\PayeServiceInterface;
use Core\Services\Interfaces\TypeAnoServiceInterface;
use Core\Services\Interfaces\TableServiceInterface;
use Core\Services\Interfaces\ObjectifSpecifiqueServiceInterface;
use Core\Services\Interfaces\ObjectifGlobauxServiceInterface;
use Core\Services\Interfaces\ResultatServiceInterface;
use Core\Services\Interfaces\FormulaireServiceInterface;
use Core\Services\Interfaces\RappelServiceInterface;
use Core\Services\Interfaces\AlerteConfigServiceInterface;
use Core\Services\Interfaces\PtabScopeServiceInterface;
use Core\Services\Interfaces\ReponseAnoServiceInterface;
use Core\Services\Interfaces\ReponseServiceInterface;
use Core\Services\Interfaces\AuditServiceInterface;
use Core\Services\Interfaces\CritereDeGouvernanceServiceInterface;
use Core\Services\Interfaces\EnqueteDeCollecteServiceInterface;
use Core\Services\Interfaces\enquetes_de_gouvernance\ActionAMenerServiceInterface as ActionAMenerGouvernanceServiceInterface;
use Core\Services\Interfaces\enquetes_de_gouvernance\CritereDeGouvernanceFactuelServiceInterface;
use Core\Services\Interfaces\enquetes_de_gouvernance\EvaluationDeGouvernanceServiceInterface as EvaluationDeGouvernanceServiceEnqueteInterface;
use Core\Services\Interfaces\enquetes_de_gouvernance\FormulaireDePerceptionDeGouvernanceServiceInterface;
use Core\Services\Interfaces\enquetes_de_gouvernance\FormulaireFactuelDeGouvernanceServiceInterface;
use Core\Services\Interfaces\enquetes_de_gouvernance\IndicateurDeGouvernanceFactuelServiceInterface;
use Core\Services\Interfaces\enquetes_de_gouvernance\OptionDeReponseGouvernanceServiceInterface;
use Core\Services\Interfaces\enquetes_de_gouvernance\PrincipeDeGouvernanceFactuelServiceInterface;
use Core\Services\Interfaces\enquetes_de_gouvernance\PrincipeDeGouvernancePerceptionServiceInterface;
use Core\Services\Interfaces\enquetes_de_gouvernance\QuestionOperationnelleServiceInterface;
use Core\Services\Interfaces\enquetes_de_gouvernance\RecommandationServiceInterface as RecommandationGouvernanceServiceInterface;
use Core\Services\Interfaces\enquetes_de_gouvernance\SoumissionDePerceptionServiceInterface;
use Core\Services\Interfaces\enquetes_de_gouvernance\SoumissionFactuelServiceInterface;
use Core\Services\Interfaces\enquetes_de_gouvernance\SourceDeVerificationServiceInterface as EnqueteSourceDeVerificationServiceInterface;
use Core\Services\Interfaces\enquetes_de_gouvernance\SurveyFormServiceInterface as EnqueteSurveyFormServiceInterface;
use Core\Services\Interfaces\enquetes_de_gouvernance\SurveyReponseServiceInterface as EnqueteSurveyReponseServiceInterface;
use Core\Services\Interfaces\enquetes_de_gouvernance\SurveyServiceInterface as EnqueteSurveyServiceInterface;
use Core\Services\Interfaces\enquetes_de_gouvernance\TypeDeGouvernanceFactuelServiceInterface;
use Core\Services\Interfaces\EvaluationDeGouvernanceServiceInterface;
use Core\Services\Interfaces\FicheDeSyntheseServiceInterface;
use Core\Services\Interfaces\FondServiceInterface;
use Core\Services\Interfaces\FormulaireDeGouvernanceServiceInterface;
use Core\Services\Interfaces\IndicateurDeGouvernanceServiceInterface;
use Core\Services\Interfaces\IndicateurValueKeyServiceInterface;
use Core\Services\Interfaces\OptionDeReponseServiceInterface;
use Core\Services\Interfaces\OrganisationServiceInterface;
use Core\Services\Interfaces\PrincipeDeGouvernanceServiceInterface;
use Core\Services\Interfaces\RecommandationServiceInterface;
use Core\Services\Interfaces\TypeDeGouvernanceServiceInterface;

use Core\Services\Interfaces\SoumissionServiceInterface;
use Core\Services\Interfaces\SourceDeVerificationServiceInterface;
use Core\Services\Interfaces\SurveyServiceInterface;
use Core\Services\Interfaces\SurveyFormServiceInterface;
use Core\Services\Interfaces\SurveyReponseServiceInterface;
use Illuminate\Support\ServiceProvider;

class RepositoryServiceProvider extends ServiceProvider
{
    /**
     * Register services.
     *
     * @return void
     */
    public function register()
    {
        $this->app->bind(EloquentRepositoryInterface::class, BaseRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, UserRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, UniteeMesureRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, RoleRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, PermissionRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, IndicateurRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, IndicateurModRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, CategorieRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, MaitriseOeuvreRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, SiteRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, UserRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, ProgrammeRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, ProjetRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, StatutRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, DureeRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, ComposanteRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, ActiviteRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, EActiviteRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, EActiviteModRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, ESuiviActiviteModRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, ValeurCibleIndicateurRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, SuiviIndicateurRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, SuiviIndicateurMODRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, TacheRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, SuiviRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, ESuiviRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, AnoRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, FichierRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, PlanDecaissementRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, DecaissementRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, BailleurRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, SuiviFinancierRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, SuiviFinancierMODRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, UniteeDeGestionRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, OngComRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, CheckListComRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, CheckListRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, SuiviCheckListComRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, PassationRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, SinistreRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, ProprieteRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, NouvelleProprieteRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, PayeRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, TypeAnoRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, GouvernementRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, ObjectifSpecifiqueRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, ObjectifGlobauxRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, ResultatRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, FormulaireRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, RappelRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, AlerteConfigRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, ReponseRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, AuditRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, IndicateurValeurRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, IndicateurValueKeyRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, OrganisationRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, TypeDeGouvernanceRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, PrincipeDeGouvernanceRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, CritereDeGouvernanceRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, IndicateurDeGouvernanceRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, OptionDeReponseRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, EnqueteDeCollecteRepository::class);

        $this->app->bind(EloquentRepositoryInterface::class, SourceDeVerificationRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, ActionAMenerRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, RecommandationRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, EvaluationDeGouvernanceRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, FormulaireDeGouvernanceRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, FondRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, SoumissionRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, FicheDeSyntheseRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, SurveyRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, SurveyFormRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, SurveyReponseRepository::class);

        $this->app->bind(AbstractServiceInterface::class, BaseService::class);
        $this->app->bind(UserServiceInterface::class, UserService::class);
        $this->app->bind(AuthServiceInterface::class, AuthService::class);
        $this->app->bind(RoleServiceInterface::class, RoleService::class);
        $this->app->bind(PermissionServiceInterface::class, PermissionService::class);
        $this->app->bind(CategorieServiceInterface::class, CategorieService::class);
        $this->app->bind(IndicateurServiceInterface::class, IndicateurService::class);
        $this->app->bind(IndicateurModServiceInterface::class, IndicateurModService::class);
        $this->app->bind(ProjetServiceInterface::class, ProjetService::class);
        $this->app->bind(TacheServiceInterface::class, TacheService::class);
        $this->app->bind(PlanDecaissementServiceInterface::class, PlanDecaissementService::class);
        $this->app->bind(DecaissementServiceInterface::class, DecaissementService::class);
        $this->app->bind(ComposanteServiceInterface::class, ComposanteService::class);
        $this->app->bind(ActiviteServiceInterface::class, ActiviteService::class);
        $this->app->bind(EActiviteServiceInterface::class, EActiviteService::class);
        $this->app->bind(EActiviteModServiceInterface::class, EActiviteModService::class);
        $this->app->bind(ESuiviActiviteModServiceInterface::class, ESuiviActiviteModService::class);
        $this->app->bind(SuiviServiceInterface::class, SuiviService::class);
        $this->app->bind(ESuiviServiceInterface::class, ESuiviService::class);
        $this->app->bind(SuiviFinancierServiceInterface::class, SuiviFinancierService::class);
        $this->app->bind(SuiviFinancierMODServiceInterface::class, SuiviFinancierMODService::class);
        $this->app->bind(ProgrammeServiceInterface::class, ProgrammeService::class);
        $this->app->bind(PtaServiceInterface::class, PtaService::class);
        $this->app->bind(FichierServiceInterface::class, FichierService::class);
        $this->app->bind(MaitriseOeuvreServiceInterface::class, MaitriseOeuvreService::class);
        $this->app->bind(SiteServiceInterface::class, SiteService::class);
        $this->app->bind(SuiviIndicateurServiceInterface::class, SuiviIndicateurService::class);
        $this->app->bind(SuiviIndicateurMODServiceInterface::class, SuiviIndicateurMODService::class);
        $this->app->bind(StatutServiceInterface::class, StatutService::class);
        $this->app->bind(AnoServiceInterface::class, AnoService::class);
        $this->app->bind(BailleurServiceInterface::class, BailleurService::class);
        $this->app->bind(UniteeDeGestionServiceInterface::class, UniteeDeGestionService::class);
        $this->app->bind(UniteeMesureServiceInterface::class, UniteeMesureService::class);
        $this->app->bind(InstitutionServiceInterface::class, InstitutionService::class);
        $this->app->bind(EntrepriseExecutantServiceInterface::class, EntrepriseExecutantService::class);
        $this->app->bind(MissionDeControleServiceInterface::class, MissionDeControleService::class);
        $this->app->bind(MembreUniteeDeGestionServiceInterface::class, MembreUniteeDeGestionService::class);
        $this->app->bind(MembreMissionDeControleServiceInterface::class, MembreMissionDeControleService::class);
        $this->app->bind(ModServiceInterface::class, ModService::class);
        $this->app->bind(OngCommServiceInterface::class, OngCommService::class);
        $this->app->bind(CheckListComServiceInterface::class, CheckListComService::class);
        $this->app->bind(CheckListServiceInterface::class, CheckListService::class);
        $this->app->bind(SuiviCheckListComServiceInterface::class, SuiviCheckListComService::class);
        $this->app->bind(PassationServiceInterface::class, PassationService::class);
        $this->app->bind(SinistreServiceInterface::class, SinistreService::class);
        $this->app->bind(ProprieteServiceInterface::class, ProprieteService::class);
        $this->app->bind(NouvelleProprieteServiceInterface::class, NouvelleProprieteService::class);
        $this->app->bind(PayeServiceInterface::class, PayeService::class);
        $this->app->bind(TypeAnoServiceInterface::class, TypeAnoService::class);
        $this->app->bind(TableServiceInterface::class, TableService::class);
        $this->app->bind(GouvernementServiceInterface::class, GouvernementService::class);
        $this->app->bind(ObjectifSpecifiqueServiceInterface::class, ObjectifSpecifiqueService::class);
        $this->app->bind(ObjectifGlobauxServiceInterface::class, ObjectifGlobauxService::class);
        $this->app->bind(ResultatServiceInterface::class, ResultatService::class);
        $this->app->bind(IndicateurCadreLogiqueServiceInterface::class, IndicateurCadreLogiqueService::class);
        $this->app->bind(FormulaireServiceInterface::class, FormulaireService::class);
        $this->app->bind(RappelServiceInterface::class, RappelService::class);
        $this->app->bind(AlerteConfigServiceInterface::class, AlerteConfigService::class);
        $this->app->bind(ReponseAnoServiceInterface::class, ReponseAnoService::class);
        $this->app->bind(PtabScopeServiceInterface::class, PtabScopeService::class);
        $this->app->bind(ReponseServiceInterface::class, ReponseService::class);
        $this->app->bind(AuditServiceInterface::class, AuditService::class);

        $this->app->bind(OrganisationServiceInterface::class, OrganisationService::class);
        $this->app->bind(TypeDeGouvernanceServiceInterface::class, TypeDeGouvernanceService::class);
        $this->app->bind(PrincipeDeGouvernanceServiceInterface::class, PrincipeDeGouvernanceService::class);
        $this->app->bind(CritereDeGouvernanceServiceInterface::class, CritereDeGouvernanceService::class);
        $this->app->bind(IndicateurDeGouvernanceServiceInterface::class, IndicateurDeGouvernanceService::class);
        $this->app->bind(OptionDeReponseServiceInterface::class, OptionDeReponseService::class);
        $this->app->bind(EnqueteDeCollecteServiceInterface::class, EnqueteDeCollecteService::class);
        $this->app->bind(IndicateurValueKeyServiceInterface::class, IndicateurValueKeyService::class);

        $this->app->bind(SourceDeVerificationServiceInterface::class, SourceDeVerificationService::class);
        $this->app->bind(SoumissionServiceInterface::class, SoumissionService::class);
        $this->app->bind(EvaluationDeGouvernanceServiceInterface::class, EvaluationDeGouvernanceService::class);

        $this->app->bind(FondServiceInterface::class, FondService::class);
        $this->app->bind(FormulaireDeGouvernanceServiceInterface::class, FormulaireDeGouvernanceService::class);


        $this->app->bind(FicheDeSyntheseServiceInterface::class, FicheDeSyntheseService::class);
        $this->app->bind(RecommandationServiceInterface::class, RecommandationService::class);
        $this->app->bind(ActionAMenerServiceInterface::class, ActionAMenerService::class);


        $this->app->bind(SurveyServiceInterface::class, SurveyService::class);
        $this->app->bind(SurveyFormServiceInterface::class, SurveyFormService::class);
        $this->app->bind(SurveyReponseServiceInterface::class, SurveyReponseService::class);

        $this->gouvernanceDependancesInjection();
    }

    protected function gouvernanceDependancesInjection(){

        $this->app->bind(EloquentRepositoryInterface::class, EnqueteActionAMenerRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, CritereDeGouvernanceFactuelRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, EnqueteEvaluationDeGouvernanceRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, EnqueteFicheDeSyntheseRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, FormulaireFactuelDeGouvernanceRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, FormulaireDePerceptionDeGouvernanceRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, IndicateurDeGouvernanceFactuelRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, OptionDeReponseGouvernanceRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, PrincipeDeGouvernanceFactuelRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, PrincipeDeGouvernancePerceptionRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, QuestionDePerceptionDeGouvernanceRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, QuestionFactuelDeGouvernanceRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, QuestionOperationnelleRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, EnqueteRecommandationRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, SoumissionDePerceptionRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, SoumissionFactuelRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, EnqueteSourceDeVerificationRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, EnqueteSurveyRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, EnqueteSurveyFormRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, EnqueteSurveyReponseRepository::class);
        $this->app->bind(EloquentRepositoryInterface::class, TypeDeGouvernanceFactuelRepository::class);


        $this->app->bind(TypeDeGouvernanceFactuelServiceInterface::class, TypeDeGouvernanceFactuelService::class);
        $this->app->bind(PrincipeDeGouvernanceFactuelServiceInterface::class, PrincipeDeGouvernanceFactuelService::class);
        $this->app->bind(PrincipeDeGouvernancePerceptionServiceInterface::class, PrincipeDeGouvernancePerceptionService::class);
        $this->app->bind(CritereDeGouvernanceFactuelServiceInterface::class, CritereDeGouvernanceFactuelService::class);
        $this->app->bind(IndicateurDeGouvernanceFactuelServiceInterface::class, IndicateurDeGouvernanceFactuelService::class);
        $this->app->bind(QuestionOperationnelleServiceInterface::class, QuestionOperationnelleService::class);
        $this->app->bind(OptionDeReponseGouvernanceServiceInterface::class, OptionDeReponseGouvernanceService::class);
        $this->app->bind(FormulaireFactuelDeGouvernanceServiceInterface::class, FormulaireFactuelDeGouvernanceService::class);
        $this->app->bind(FormulaireDePerceptionDeGouvernanceServiceInterface::class, FormulaireDePerceptionDeGouvernanceService::class);

        $this->app->bind(EnqueteSourceDeVerificationServiceInterface::class, EnqueteSourceDeVerificationService::class);

        $this->app->bind(EvaluationDeGouvernanceServiceEnqueteInterface::class, EvaluationDeGouvernanceEnqueteService::class);

        $this->app->bind(SoumissionFactuelServiceInterface::class, SoumissionFactuelService::class);
        $this->app->bind(SoumissionDePerceptionServiceInterface::class, SoumissionDePerceptionService::class);

        $this->app->bind(RecommandationGouvernanceServiceInterface::class, RecommandationGouvernanceService::class);
        $this->app->bind(ActionAMenerGouvernanceServiceInterface::class, ActionAMenerGouvernanceService::class);


        $this->app->bind(EnqueteSurveyServiceInterface::class, EnqueteSurveyService::class);
        $this->app->bind(EnqueteSurveyFormServiceInterface::class, EnqueteSurveyFormService::class);
        $this->app->bind(EnqueteSurveyReponseServiceInterface::class, EnqueteSurveyReponseService::class);

    }

    /**
     * Bootstrap services.
     *
     * @return void
     */
    public function boot()
    {
        //
    }
}
